# Generated by Django 4.1 on 2023-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelimg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel",
            name="photo",
            field=models.ImageField(default=0, upload_to="photos/"),
            preserve_default=False,
        ),
    ]
