# Generated by Django 4.2.3 on 2023-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelimg', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='photo',
            field=models.ImageField(upload_to='../../Documents/img'),
        ),
    ]
